# Generated by Django 3.1.4 on 2021-03-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('totalTime', models.DateField()),
                ('allNumber', models.IntegerField()),
                ('number', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
                ('starts', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'resvideo',
            },
        ),
    ]
