# Generated by Django 3.1.7 on 2021-04-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tSeries',
            fields=[
                ('sID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('starts', models.CharField(max_length=500)),
                ('allNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'tSeries',
            },
        ),
        migrations.CreateModel(
            name='tVideo',
            fields=[
                ('uploadID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('h5Path', models.CharField(max_length=500, unique=True)),
                ('path', models.CharField(max_length=500, unique=True)),
                ('vTime', models.TimeField()),
                ('inputTime', models.DateTimeField()),
                ('sID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.tseries')),
            ],
            options={
                'db_table': 'tVideo',
            },
        ),
    ]
