# Generated by Django 3.1.4 on 2021-03-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resvideo',
            name='totalTime',
            field=models.TimeField(),
        ),
    ]
