# Generated by Django 3.1.7 on 2021-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20210328_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='resvideo',
            name='h5Path',
            field=models.CharField(default='', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
