# Generated by Django 3.1.7 on 2021-04-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20210405_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvideo',
            name='h5Path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tvideo',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
