# Generated by Django 3.1.7 on 2021-04-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_resvideo_h5path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resvideo',
            name='id',
        ),
        migrations.AddField(
            model_name='resvideo',
            name='uploadID',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
