# Generated by Django 3.1.7 on 2021-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_auto_20210402_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='resvideo',
            name='addTime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
